# Generated by Django 4.2 on 2023-05-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0004_profile_contact_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
