# Generated by Django 4.2 on 2023-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_img',
            field=models.ImageField(upload_to='media/item_image'),
        ),
    ]
