# Generated by Django 4.2 on 2023-06-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0019_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
