# Generated by Django 4.2 on 2023-06-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0023_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOmeterApp.profile'),
        ),
    ]
