# Generated by Django 4.2 on 2023-06-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0033_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='t_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
