# Generated by Django 4.2 on 2023-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0036_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='qantity',
            field=models.IntegerField(default=0),
        ),
    ]
