# Generated by Django 4.2 on 2023-06-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0039_cart_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodOmeterApp.cartitems'),
        ),
    ]
