# Generated by Django 4.2 on 2023-06-02 16:05

from django.db import migrations, models
import foodOmeterApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodOmeterApp', '0041_remove_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=foodOmeterApp.models.CartItems),
        ),
    ]
